[pytest]
addopts = --embedded-services esp,idf --target esp32s3
markers =
    supported_targets: mark test as supported targets
    preview_targets: mark test as preview targets
    generic: mark test as generic
    esp: espressif soc
    idf: espressif idf
